TOP=..
include $(TOP)/configure/CONFIG

DIRS := cpr

#----------------------------------------
#  ADD MACRO DEFINITIONS AFTER THIS LINE
#=============================

SRC_DIRS += ./json

INC += json.hpp
INC += json_fwd.hpp

#=============================

include $(TOP)/configure/RULES
#----------------------------------------
#  ADD RULES AFTER THIS LINE
